// Array com as logos dos times
export const teams_logos = [
  {
    name: 'Valladolid',
    logo: 'https://upload.wikimedia.org/wikipedia/pt/5/5d/Real_Valladolid_CF.png',
  },
  {
    name: 'Las-Palmas',
    logo: 'https://upload.wikimedia.org/wikipedia/pt/d/d2/UD_Las_Palmas.png',
  },
  {
    name: 'Stuttgart',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/eb/VfB_Stuttgart_1893_Logo.svg',
  },
  {
    name: 'Bayern Munich',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg',
  },
  {
    name:'West Ham',
    logo:'https://upload.wikimedia.org/wikipedia/pt/1/1d/West_Ham_United_FC_logo.png',
  },
  {
    name:'Leicester City',
    logo:'https://upload.wikimedia.org/wikipedia/pt/0/0e/LeicesterCity_logo2014.png',
  },
  {
    name:'Bologna',
    logo:'https://upload.wikimedia.org/wikipedia/commons/5/5b/Bologna_F.C._1909_logo.svg',
  },
  {
    name:'Milan',
    logo:'https://upload.wikimedia.org/wikipedia/commons/d/d0/Logo_of_AC_Milan.svg',
  },
  {
    name:'Fiorentina',
    logo:'https://upload.wikimedia.org/wikipedia/commons/8/8c/ACF_Fiorentina_-_logo_%28Italy%2C_2022%29.svg',
  },
  {
    name:'Lecce',
    logo:'https://upload.wikimedia.org/wikipedia/pt/6/6e/US_Lecce.png',
  },
  {
    name:'Monaco',
    logo:'https://upload.wikimedia.org/wikipedia/en/c/cf/LogoASMonacoFC2021.svg',
  },
  {
    name:'Reims',
    logo:'https://upload.wikimedia.org/wikipedia/pt/c/cb/Stade_de_Reims.png',
  },
  {
    name:'Girona',
    logo:'https://upload.wikimedia.org/wikipedia/pt/5/5d/Girona_FC.png',
  },
  {
    name:'Celta-Vigo',
    logo:'https://upload.wikimedia.org/wikipedia/pt/3/3d/Celta_de_Vigo.png',
  },
   {
    name:'Cadiz',
    logo:'https://upload.wikimedia.org/wikipedia/pt/e/eb/C%C3%A1diz_Club_de_F%C3%BAtbol_logo.png',
  },
  {
    name:'Leganes',
    logo:'https://upload.wikimedia.org/wikipedia/pt/2/2e/CD_Legan%C3%A9s.png',
  },
  {
    name:'Almeria',
    logo:'https://upload.wikimedia.org/wikipedia/pt/b/b7/UD_Almeria.png',
  },
  {
    name:'Granada',
    logo:'https://upload.wikimedia.org/wikipedia/pt/9/9a/Granada_FC_logo.png',
  },
  {
    name:'Rayo-Vallecano',
    logo:'https://upload.wikimedia.org/wikipedia/pt/b/b2/Rayo_Vallecano_de_Madrid.png',
  },
  {
    name:'Sevilla',
    logo:'https://upload.wikimedia.org/wikipedia/pt/c/cd/Sevilla_cf.png',
  },
  {
    name:'Real-Betis',
    logo:'http://upload.wikimedia.org/wikipedia/pt/1/17/Real_Betis_Balompi%C3%A9.png',
  },
  {
    name:'Betis',
    logo:'http://upload.wikimedia.org/wikipedia/pt/1/17/Real_Betis_Balompi%C3%A9.png',
  },
  {
    name:'Real-Madrid',
    logo:'https://upload.wikimedia.org/wikipedia/pt/9/98/Real_Madrid.png',
  },
  {
    name:'Atletico-Madrid',
    logo:'https://upload.wikimedia.org/wikipedia/pt/c/c1/Atletico_Madrid_logo.svg',
  },
  {
    name:'Athletic-Club',
    logo:'https://upload.wikimedia.org/wikipedia/pt/9/90/Athletic_Club_de_Bilbao.png',
  },
  {
    name:'Werder Bremen',
    logo:'https://upload.wikimedia.org/wikipedia/pt/d/d0/Werder_Bremen.png',
  },
  {
    name:'Wolfsburg',
    logo:'https://upload.wikimedia.org/wikipedia/commons/f/f3/Logo-VfL-Wolfsburg.svg',
  },
  {
    name:'Bochum',
    logo:'https://upload.wikimedia.org/wikipedia/pt/5/5c/VfL-Bochum.png',
  },
  {
    name:'Hoffenheim',
    logo:'https://upload.wikimedia.org/wikipedia/commons/e/e7/Logo_TSG_Hoffenheim.svg',
  },
  {
    name:'Heidenheim',
    logo:'https://upload.wikimedia.org/wikipedia/commons/9/9d/1._FC_Heidenheim_1846.svg',
  },
  {
    name:'Gladbach',
    logo:'https://upload.wikimedia.org/wikipedia/commons/8/81/Borussia_M%C3%B6nchengladbach_logo.svg',
  },
  {
    name:'RB Leipzig',
    logo:'https://upload.wikimedia.org/wikipedia/en/0/04/RB_Leipzig_2014_logo.svg',
  },
  {
    name:'Mainz 05',
    logo:'https://upload.wikimedia.org/wikipedia/pt/5/5b/FSV_Mainz_05.png',
  },
  {
    name:'St. Pauli',
    logo:'https://upload.wikimedia.org/wikipedia/commons/b/b5/FC_St_Pauli.png',
  },
  {
    name:'Dortmund',
    logo:'https://upload.wikimedia.org/wikipedia/commons/6/67/Borussia_Dortmund_logo.svg',
  },
  {
    name:'Eint Frankfurt',
    logo:'https://upload.wikimedia.org/wikipedia/commons/e/e6/Logo_Eintracht_Frankfurt_Od_1998.gif',
  },
  {
    name:'Leverkusen',
    logo:'https://upload.wikimedia.org/wikipedia/pt/a/a2/Bayer_Leverkusen.png',
  },
  {
    name:'Atalanta',
    logo:'https://upload.wikimedia.org/wikipedia/pt/f/f6/385px-AtalantaBC.svg.png',
  },
  {
    name:'Venezia',
    logo:'https://upload.wikimedia.org/wikipedia/en/3/39/Venezia_FC_crest.svg',
  },
  {
    name:'Napoli',
    logo:'https://upload.wikimedia.org/wikipedia/commons/2/2d/SSC_Neapel.svg',
  },
  {
    name:'Inter',
    logo:'https://upload.wikimedia.org/wikipedia/commons/0/05/FC_Internazionale_Milano_2021.svg',
  },
  {
    name:'Udinese',
    logo:'https://upload.wikimedia.org/wikipedia/pt/1/19/Udinese_Calcio.png',
  },
  {
    name:'Parma',
    logo:'https://upload.wikimedia.org/wikipedia/pt/3/39/Parma_FC.png',
  },
  {
    name:'Saint-Etienne',
    logo:'https://upload.wikimedia.org/wikipedia/commons/f/fb/AS_Saint-%C3%89tienne_official_logo.png',
  },
  {
    name:'Lens',
    logo:'https://upload.wikimedia.org/wikipedia/pt/8/8d/RC_Lens.png',
  },
  {
    name:'Paris-Saint-Germain',
    logo:'https://upload.wikimedia.org/wikipedia/pt/d/d2/Logo_PSG.png',
  },
  {
    name:'Lille',
    logo:'https://upload.wikimedia.org/wikipedia/pt/7/74/Lille_osc.png',
  },
  {
    name:'Leganés',
    logo:'https://upload.wikimedia.org/wikipedia/pt/2/2e/CD_Legan%C3%A9s.png',
  },
  {
    name:'Getafe',
    logo:'https://upload.wikimedia.org/wikipedia/pt/7/7f/Getafe_logo.png',
  },
  {
    name:'Barcelona',
    logo:'https://upload.wikimedia.org/wikipedia/pt/4/43/FCBarcelona.svg',
  },
  {
    name:'Real-Sociedad',
    logo:'https://upload.wikimedia.org/wikipedia/en/f/f1/Real_Sociedad_logo.svg',
  },
  {
    name:'Mallorca',
    logo:'https://upload.wikimedia.org/wikipedia/pt/1/1d/RCD_Mallorca.png',
  },
  {
    name:'Alavés',
    logo:'https://upload.wikimedia.org/wikipedia/pt/4/44/Deportivo_Alav%C3%A9s.png',
  },
  {
    name:'Osasuna',
    logo:'https://upload.wikimedia.org/wikipedia/pt/3/39/CA_Osasuna.png',
  },
  {
    name:'Valencia',
    logo:'https://upload.wikimedia.org/wikipedia/pt/6/66/Valencia_Cf_Logo_original.png',
  },
  {
    name:'Union-Berlin',
    logo:'https://upload.wikimedia.org/wikipedia/commons/4/44/1._FC_Union_Berlin_Logo.svg',
  },
  {
    name:'Holstein-Kiel',
    logo:'https://upload.wikimedia.org/wikipedia/commons/3/30/Holstein_Kiel_Logo.svg',
  },
  {
    name:'Holstein Kiel',
    logo:'https://upload.wikimedia.org/wikipedia/commons/3/30/Holstein_Kiel_Logo.svg',
  },
  {
    name:'Augsburg',
    logo:'https://upload.wikimedia.org/wikipedia/pt/4/42/FC_Augsburg.png',
  },
  {
    name:'Freiburg',
    logo:'https://upload.wikimedia.org/wikipedia/pt/7/7b/SC_Freiburg.png',
  },
  {
    name:'Monza',
    logo:'https://upload.wikimedia.org/wikipedia/commons/3/37/Logo_of_AC_Monza.png',
  },
  {
    name:'Torino',
    logo:'https://upload.wikimedia.org/wikipedia/pt/2/2e/Torino_FC_logo.png',
  },
  {
    name:'Gladbach',
    logo:'https://upload.wikimedia.org/wikipedia/commons/8/81/Borussia_M%C3%B6nchengladbach_logo.svg',
  },
  {
    name:'Nice',
    logo:'https://upload.wikimedia.org/wikipedia/pt/d/d2/OGC_Nice.svg',
  },
  {
    name:'Le Havre',
    logo:'https://upload.wikimedia.org/wikipedia/pt/3/3d/Le_Havre_AC_logo.png',
  },
  {
    name:'Genoa',
    logo:'https://upload.wikimedia.org/wikipedia/pt/0/04/GenoaCFC.png',
  },
  {
    name:'Empoli',
    logo:'https://upload.wikimedia.org/wikipedia/commons/9/94/Empoli_FC.png',
  },
  {
    name:'Cagliari',
    logo:'https://upload.wikimedia.org/wikipedia/pt/8/86/Cagliari_Calcio_Logo_2015.png',
  },
  {
    name:'Roma',
    logo:'https://upload.wikimedia.org/wikipedia/pt/8/8c/AS_Roma_logo.png',
  },
  {
    name:'Como',
    logo:'https://upload.wikimedia.org/wikipedia/commons/2/2c/Logo_Como_1907_2019.png',
  },
  {
    name:'Lyon',
    logo:'https://upload.wikimedia.org/wikipedia/pt/6/6d/Olympique_lyonnais.png',
  },
  {
    name:'Lazio',
    logo:'https://upload.wikimedia.org/wikipedia/pt/e/ed/SS_Lazio.png',
  },
  {
    name:'Brest',
    logo:'https://upload.wikimedia.org/wikipedia/pt/4/4e/SB29_logo.png',
  },
  {
    name:'Auxerre',
    logo:'https://upload.wikimedia.org/wikipedia/pt/a/a8/AJ_Auxerre.png',
  },
  {
    name:'Strasbourg',
    logo:'https://upload.wikimedia.org/wikipedia/en/8/80/Racing_Club_de_Strasbourg_logo.svg',
  },
  {
    name:'Montpellier',
    logo:'https://upload.wikimedia.org/wikipedia/pt/8/83/MontpellierHSC_logo.png',
  },
  {
    name:'Rennes',
    logo:'https://upload.wikimedia.org/wikipedia/pt/a/ad/Stade_Rennais_FC.png',
  },
  {
    name:'Angers',
    logo:'https://upload.wikimedia.org/wikipedia/it/d/dc/Angers_SCO_logo_2021.png',
  },
  {
    name:'Toulouse',
    logo:'https://upload.wikimedia.org/wikipedia/pt/8/8b/Toulouse_FC.png',
  },
  {
    name:'Marseille',
    logo:'https://upload.wikimedia.org/wikipedia/commons/d/d8/Olympique_Marseille_logo.svg',
  },
  {
    name:'Nantes',
    logo:'https://upload.wikimedia.org/wikipedia/commons/6/68/FC-Nantes-blason-rvb.png',
  },
  {
    name:'Villarreal',
    logo:'https://upload.wikimedia.org/wikipedia/pt/7/70/Villarreal_CF_logo.svg',
  },
  {
    name:'Espanyol',
    logo:'https://upload.wikimedia.org/wikipedia/pt/2/29/Rcd_espanyol_logo.png',
  },
  {
    name:'Juventus',
    logo:'https://upload.wikimedia.org/wikipedia/commons/5/51/Juventus_FC_2017_logo.png',
  },
  {
    name:'Hellas-Verona',
    logo:'https://upload.wikimedia.org/wikipedia/en/9/92/Hellas_Verona_FC_logo_%282020%29.svg',
  },
  {
    name:'Chelsea',
    logo:'https://upload.wikimedia.org/wikipedia/pt/c/cc/Chelsea_FC.svg',
  },
  {
    name:'Tottenham',
    logo:'https://upload.wikimedia.org/wikipedia/pt/6/6d/Tottenham_Hotspur.png',
  },
  {
    name:'Arsenal',
    logo:'https://upload.wikimedia.org/wikipedia/pt/5/53/Arsenal_FC.svg',
  },
  {
    name:'Manchester-Utd',
    logo:'https://upload.wikimedia.org/wikipedia/pt/b/b6/Manchester_United_FC_logo.png',
  },
  {
    name:'Newcastle-Utd',
    logo:'https://upload.wikimedia.org/wikipedia/en/5/56/Newcastle_United_Logo.svg',
  },
  {
    name:'Bournemouth',
    logo:'https://upload.wikimedia.org/wikipedia/pt/9/98/AfcBournemouth.png',
  },
  {
    name:'Bayer-Leverkusen',
    logo:'https://upload.wikimedia.org/wikipedia/pt/a/a2/Bayer_Leverkusen.png',
  },
  {
    name:'Paris-Saint-Germain',
    logo:'https://upload.wikimedia.org/wikipedia/pt/d/d2/Logo_PSG.png',
  },
  {
    name:'Internazionale',
    logo:'https://upload.wikimedia.org/wikipedia/commons/0/05/FC_Internazionale_Milano_2021.svg',
  },
  {
    name:'Liverpool',
    logo:'https://upload.wikimedia.org/wikipedia/pt/0/0c/Liverpool_FC.svg',
  },
  {
    name:'Manchester-City',
    logo:'https://upload.wikimedia.org/wikipedia/pt/0/02/Manchester_City_Football_Club.png',
  },
   {
    name:'Manchester City',
    logo:'https://upload.wikimedia.org/wikipedia/pt/0/02/Manchester_City_Football_Club.png',
  },
  {
    name:'Tottenham-Hotspur',
    logo:'https://upload.wikimedia.org/wikipedia/pt/6/6d/Tottenham_Hotspur.png',
  },
  {
    name:'Atletico-Madrid',
    logo:'https://upload.wikimedia.org/wikipedia/pt/c/c1/Atletico_Madrid_logo.svg',
  },
  {
    name:'Alaves',
    logo:'https://upload.wikimedia.org/wikipedia/en/f/f8/Deportivo_Alaves_logo_%282020%29.svg',
  },
  {
    name:'Bahia',
    logo:'https://upload.wikimedia.org/wikipedia/pt/9/90/ECBahia.png',
  },

  {
    name:'Champions-League',
    logo:'https://toppng.com/uploads/preview/champions-league-logo-png-uefa-champions-league-logo-png-white-11562854628nhnxjr3ofn.png',
  },
  {
    name:'Copa-del-Rey',
    logo:'https://upload.wikimedia.org/wikipedia/commons/b/ba/Copa_Del_Rey_Official_Logo.png',
  },
   {
    name:'Ligue-1',
    logo:'https://upload.wikimedia.org/wikipedia/commons/5/5e/Ligue1.svg',
  },
  {
    name:'Metz',
    logo:'https://upload.wikimedia.org/wikipedia/commons/4/4a/FC_Metz_2021_Logo.svg',
  },
{
    name:'Clermont-Foot',
    logo:'https://upload.wikimedia.org/wikipedia/pt/2/21/Clermont_Foot_63_logo.png',
  },
  {
    name:'Lorient',
    logo:'https://upload.wikimedia.org/wikipedia/pt/a/a6/FC_Lorient.png',
  },
  {
    name:'Benfica',
    logo:'https://upload.wikimedia.org/wikipedia/pt/d/de/Sport_Lisboa_e_Benfica.svg',
  },
  {
    name:'Salzburg',
    logo:'https://upload.wikimedia.org/wikipedia/pt/1/14/FCSalzburg.png',
  },
  {
    name:'RB-Salzburg',
    logo:'https://upload.wikimedia.org/wikipedia/pt/1/14/FCSalzburg.png',
  },
  {
    name: "Nottingham-Forest",
    logo:'https://upload.wikimedia.org/wikipedia/pt/a/a2/Nottingham_Forest.png',
  },


];

